/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author ASUS
 */
public class frameUtama extends javax.swing.JFrame {

    /**
     * Creates new form frameutama
     */
    public frameUtama() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmabsen = new javax.swing.JButton();
        frmgajipokok = new javax.swing.JButton();
        frmjabatan = new javax.swing.JButton();
        frmkaryawan = new javax.swing.JButton();
        frmpenggajian = new javax.swing.JButton();
        frmtunjangan = new javax.swing.JButton();
        frmuser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frmabsen.setText("Form Absen");
        frmabsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmabsenActionPerformed(evt);
            }
        });

        frmgajipokok.setText("Form Gaji Pokok");
        frmgajipokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmgajipokokActionPerformed(evt);
            }
        });

        frmjabatan.setText("Form Jabatan");
        frmjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmjabatanActionPerformed(evt);
            }
        });

        frmkaryawan.setText("Form Karyawan");
        frmkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmkaryawanActionPerformed(evt);
            }
        });

        frmpenggajian.setText("Form Penggajian");
        frmpenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmpenggajianActionPerformed(evt);
            }
        });

        frmtunjangan.setText("Form Tunjangan");
        frmtunjangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmtunjanganActionPerformed(evt);
            }
        });

        frmuser.setText("Form User");
        frmuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmuserActionPerformed(evt);
            }
        });

        jLabel1.setText("MAIN MENU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frmuser)
                            .addComponent(frmtunjangan)
                            .addComponent(frmpenggajian)
                            .addComponent(frmkaryawan)
                            .addComponent(frmjabatan)
                            .addComponent(frmabsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(frmgajipokok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {frmabsen, frmgajipokok, frmjabatan, frmkaryawan, frmpenggajian, frmtunjangan, frmuser});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(frmabsen)
                .addGap(18, 18, 18)
                .addComponent(frmgajipokok)
                .addGap(18, 18, 18)
                .addComponent(frmjabatan)
                .addGap(18, 18, 18)
                .addComponent(frmkaryawan)
                .addGap(18, 18, 18)
                .addComponent(frmpenggajian)
                .addGap(18, 18, 18)
                .addComponent(frmtunjangan)
                .addGap(18, 18, 18)
                .addComponent(frmuser)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frmabsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmabsenActionPerformed
        frameAbsen frmabsen = new frameAbsen();
        frmabsen.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_frmabsenActionPerformed

    private void frmgajipokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmgajipokokActionPerformed

        frameGajiPokok frmgajipokok = new frameGajiPokok();
        frmgajipokok.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_frmgajipokokActionPerformed

    private void frmjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmjabatanActionPerformed

        frameJabatan frmjabatan = new frameJabatan();
        frmjabatan.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_frmjabatanActionPerformed

    private void frmkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmkaryawanActionPerformed

        frameKaryawan frmkaryawan = new frameKaryawan();
        frmkaryawan.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_frmkaryawanActionPerformed

    private void frmpenggajianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmpenggajianActionPerformed

        framePenggajian frmpenggajian = new framePenggajian();
        frmpenggajian.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_frmpenggajianActionPerformed

    private void frmtunjanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmtunjanganActionPerformed

        frameTunjangan frmtunjangan = new frameTunjangan();
        frmtunjangan.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_frmtunjanganActionPerformed

    private void frmuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmuserActionPerformed

        frameUser frmuser = new frameUser();
        frmuser.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_frmuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton frmabsen;
    private javax.swing.JButton frmgajipokok;
    private javax.swing.JButton frmjabatan;
    private javax.swing.JButton frmkaryawan;
    private javax.swing.JButton frmpenggajian;
    private javax.swing.JButton frmtunjangan;
    private javax.swing.JButton frmuser;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
